name: newdemo
on:
 push:
   branches:
      - main

jobs:
  jobname:
    runs-on: ubuntu-latest
    steps:
      - name: checking out branch
        uses: actions/checkout@main
      - name: test printing secrets
        run: echo ${{ secrets.MYSECRET1 }}
