name: newdemo
on: [push]
env:
 globalvar1: "globalvar1"
 globalvar2: "globalvar2"

jobs:
 BuildJob:
   runs-on: ubuntu-latest
   steps:
     - name: printing global var
       run: echo Global value $globalvar1 envlevel1 is $envlevel1
       env:
         envlevel1: "envlevel1"
