name: Java Workflow

on:
  push:
    branches:
       - main
       
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
         java-version: 11
         distribution: 'jdk'  # Specify the desired Java distribution
        
        
      - name: build
        run: javac ./gitesting/src/gitesting/MainClass.java
        
      - name: dir listing
        run: ls -lt gitesting/src/gitesting/
      
      - name: test
        run: java ./gitesting/src/gitesting/MainClass
        
      - name: uplaod artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact1
          path: ./myartifactpath
