name: newdemo
on:
 push:
   branches:
      - main

jobs:
  jobname:
    runs-on: ubuntu-latest
    steps:
      - name: checking out branch
        uses: actions/checkout@main
      
      - name: branch main 111 checkedout
        run: echo branch main 111 checked out.
