name: VaribleDemo
on: [push]
env:
    globalVar1: "Global var1 value"
    galobalVar2: "Global var2 value"
jobs:
  VariableUsageJob:
    runs-on: ubuntu-latest
    env:
      job_var1: "job var1 value"
    steps:
      - name: Using workflow variables
        run: echo Hello, $globalVar1 $globalVar2
             here is jobvar1 $job_var1
        
        env:
          step_var1: "Step level var1"
      - name: using variables
        run: echo Hello, $globalVar1
             Welcome $step_var1
