name: newdemo
on:
 push:
   branches:
      - main

jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
      - name: checking out new branch
        uses: actions/checkout@v3
        with:
          repository: hassanarifibm/gitesting
          ref: main
          path: gitesting
          token: ${{ secrets.NEWPAT }}
      - name: dir listing
        run: cd / && tree
