name: FailureCheck
on:
 push:
   branches:
      - main

jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
     - name: This step is gonig to pass by printing date
       run: date
       
     - name: Step to be failed
       run: exit 1
       
     - name: Step to run on failure
       if: ${{ failure() }}
       run: echo https://api.github.com/repos/${{ github.repository }}/issues
