name: newdemo
on:
 push:
   branches:
      - main

jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
      - name: Step is going to pass
        run: echo Passing step 

      - name: Step is going to fail
        run: echo ${{ github.run_id }}
             echo ${{ github.workflow }}
             echo ${{ github.repository }}
