name: newdemo
on:
 push:
   branches:
      - main

jobs:
  jobname:
    runs-on: ubuntu-latest
    steps:
      - name: checking out branch
        uses: actions/checkout@main
      
      - name: branch main 111 checkedout
        run: echo branch main 111 checked out.
      
      - name: checkingout another branch
        uses: actions/checkout@v3
        with:
           repository: hassanarifibm/gitesting
           ref: main
           path: hassanarifibm/gitesting
           token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: another branch checkedout
        run: echo another branch checked out
