name: My Scheduled Workflow

on:
  #schedule:
  #  - cron: '*/5 * * * *'  # Schedule to run every five minutes

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run my job
        run: echo "This is my scheduled job!"
