name: FailureCheck
on:
 push:
   branches:
      - main

jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
     - name: This step is gonig to pass by printing date
       run: date
       
     - name: Step to be failed
       run: exit 1
       
     - name: Step to run on failure
       if: ${{ failure() }}
       run: |
         curl --request POST --url https://api.github.com/repos/${{ github.repository }}/issues --header 'authorization: Bearer ${{ secret.PAT_ALL }}' \
         --header 'content-type: application/json' \
         --data '{"title": "Issue created due to workflow failure: ${{ github.run_id }}",
         "body": "This issue was automatically created by the github action workflow **${{ github.workflow }}**. \n\ndue to failure in run: ${{ github.run_id }}_."
         }'
