name: newdemo
on: [push]
env:
 globalvar1: "globalvar1"
 globalvar2: "globalvar2"

jobs:
 BuildJob:
   runs-on: ubuntu-latest
   steps:
     - name: printing global var
       run: Global value $globalvar1
