name: newdemo
on:
 push:
   branches:
      - main

jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
      - name: checking out new branch
        uses: actions/checkout@v3
        with:
          repository: hassanarifibm/gitesting
          ref: main
          path: gitesting
          token: ${{ secrets.CHECKOUT_TEST }}
      - name: dir listing
        run: cd /home/runner/work/gitest && tree
      
      - name: printing date
        run: date
